services:
  # 1. The Database (Postgres)
  db:
    image: docker.io/postgres:15-alpine
    container_name: safari_db
    environment:
      POSTGRES_USER: safari_user
      POSTGRES_PASSWORD: secure_secret_password
      POSTGRES_DB: safari_bus_db
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres_data:/var/lib/postgresql/data
    networks:
      - safari_net

  # 2. The Cache/Broker (Redis)
  redis:
    image: docker.io/redis:7-alpine
    container_name: safari_redis
    ports:
      - "6379:6379"
    networks:
      - safari_net
    volumes:
      - ./infra/redis_data:/data

  # 3. The Backend (Node.js) - Optional to containerize now, or run locally
  # backend:
  #   build: ./server
  #   container_name: safari_backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_URL=postgres://safari_user:secure_secret_password@db:5432/safari_bus_db
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - safari_net

# The shared network container to allow container to container communications
networks:
  safari_net:
    driver: bridge